# Generated by Django 3.2.18 on 2023-03-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprofile',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='car_profiles'),
        ),
    ]
