# Generated by Django 3.2.18 on 2023-03-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('displacement', models.DecimalField(decimal_places=6, max_digits=10)),
                ('year', models.PositiveIntegerField()),
                ('is_supercharged', models.BooleanField(default=False)),
                ('drag', models.DecimalField(decimal_places=6, max_digits=10)),
                ('image_url', models.ImageField(blank=True, upload_to='cars')),
            ],
        ),
    ]
