# Generated by Django 3.2.18 on 2023-03-22 22:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_profiles', '0001_initial'),
        ('user_profiles', '0004_auto_20230321_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('route_coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=None)),
                ('fuel_consumption', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('fuel_consumption_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('co2_emissions', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('n2o_emissions', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('ch4_emissions', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('car_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_profile', to='car_profiles.carprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user_profiles.userprofile')),
            ],
        ),
    ]
