# Generated by Django 3.2.18 on 2023-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='ch4_emissions',
            new_name='average_speed',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='fuel_consumption_price',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='n2o_emissions',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='route_coordinates',
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.JSONField(default=list),
        ),
    ]
