# Generated by Django 3.2.18 on 2023-04-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20230402_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='route',
            new_name='route_coordinates',
        ),
    ]
